algoritmo "Leitura de dados" //ajeitar projeto

var 
   nome, email: caractere
   idade: inteiro
inicio
       escreva("Nome? ")
    leia(nome)
       escreval(a, " ")
    leia(nome)
       escreva("Idade? ")
    leia(idade)
       escreval(b, " ")
    leia(email)
       escreva("Email? ")
       escreval(c, " ")
       escreval(" ")
    escreva("  Seja bem-vindo ", a, ", obrigado por escolher nossos serviços! (°o°)")

fimalgoritmo